Repository GalacticsTeam/galactics-bot-enhanced, pull requests merged in 2024-09, with the labels that each got.

#61 Fixes
  src/actionHandlers/commands/avatar.ts
  src/actionHandlers/commands/maintenance.ts
  src/actionHandlers/index.ts
  src/actionHandlers/onRoleOrganize.ts
  src/actionHandlers/onTempChannel/onEveryTempChannel.ts
  src/utils/helpers.ts
Labels: bug, enhancement, refactor

#62 [GTB-73] Morse Translator Interaction Implementation
  .prettierrc.json
  src/actionHandlers/commands/commands.ts
  src/actionHandlers/commands/morseTranslate.ts
  src/actionHandlers/index.ts
  src/actionHandlers/onMorseTranslate/const.ts
  src/actionHandlers/onMorseTranslate/helpers.ts
  src/actionHandlers/onMorseTranslate/index.ts
  src/utils/botConfig.ts
  src/utils/const.ts
Labels: enhancement, feature

#64 Testing pipline Flow
  .github/workflows/deploy.yml
  .github/workflows/tests.yml
  .husky/pre-commit
  eslint.config.mjs
  package-lock.json
  package.json
  src/actionHandlers/commands/index.ts
  src/actionHandlers/onCustomStatus.ts
  src/actionHandlers/onLinkSend.ts
  src/actionHandlers/onMorseTranslate/const.ts
  src/actionHandlers/onPing.ts
  src/actionHandlers/onServerConfig/index.ts
  src/actionHandlers/onTempChannel/onEveryTempChannel.ts
  src/actionHandlers/onTempChannel/onTempChannel.ts
  src/actions/onMessageCreate.ts
  src/actions/types.ts
  src/db/helpers.ts
  src/db/types.ts
  src/localdb/helpers.ts
  src/utils/botConfig.ts
  src/utils/const.ts
  src/utils/helpers.ts
Labels: enhancement, feature, refactor

#66 [GTB-89] Bot Config Simplification
  src/actionHandlers/onCustomStatus.ts
  src/const.ts
  src/localdb/helpers.ts
  src/localdb/index.ts
  src/types.ts
  src/utils/botConfig.ts
Labels: enhancement, refactor

#67 Typescript Support for duplicates Config
  src/actionHandlers/onCustomStatus.ts
  src/const.ts
  src/localdb/helpers.ts
  src/localdb/index.ts
  src/types.ts
  src/utils/botConfig.ts
Labels: enhancement, refactor
