Repository GalacticsTeam/galactics-bot-enhanced, pull requests merged in 2024-07, with the labels that each got.

#48 [GTB-5] warning system implementation
  src/actionHandlers/commands/index.ts
  src/actionHandlers/commands/warn.ts
  src/utils/botConfig.ts
Labels: enhancement, feature

#50 [GTB-61] Live server statuses implementation
  package.json
  src/actionHandlers/commands/index.ts
  src/actionHandlers/commands/serverStatus.ts
  src/actionHandlers/index.ts
  src/actionHandlers/onServerStatus/helpers.ts
  src/actionHandlers/onServerStatus/index.ts
  src/actionHandlers/onServerStatus/removeStatus.ts
  src/actionHandlers/onServerStatus/types.ts
  src/actions/index.ts
  src/db/ServerSchema.ts
  src/localdb/index.ts
  src/types.ts
  src/utils/botConfig.ts
Labels: enhancement, feature

#49 [GTB-67] Interval System Implementation
  package.json
  src/actionHandlers/commands/index.ts
  src/actionHandlers/commands/serverStatus.ts
  src/actionHandlers/index.ts
  src/actionHandlers/onServerStatus/helpers.ts
  src/actionHandlers/onServerStatus/index.ts
  src/actionHandlers/onServerStatus/removeStatus.ts
  src/actionHandlers/onServerStatus/types.ts
  src/actions/action.ts
  src/actions/index.ts
  src/actions/types.ts
  src/db/ServerSchema.ts
  src/localdb/index.ts
  src/types.ts
  src/utils/botConfig.ts
Labels: enhancement, feature

#51 feat: enhance file imports and local db handling
  localdb/db.json
  package-lock.json
  package.json
  src/actionHandlers/commands/warn.ts
  src/actionHandlers/index.ts
  src/actions/onGuildMemberAdd.ts
  src/types.ts
  src/utils/helpers.ts
Labels: enhancement, refactor

#52 Status Channel Deletion or invalidity handling
  src/actionHandlers/onServerStatus/index.ts
  src/actions/index.ts
Labels: bug, enhancement, refactor

#53 Temp channels system
  src/actionHandlers/index.ts
  src/actionHandlers/onTempChannel/helpers.ts
  src/actionHandlers/onTempChannel/index.ts
  src/actionHandlers/onTempChannel/onEveryTempChannel.ts
  src/actionHandlers/onTempChannel/onTempChannel.ts
  src/actionHandlers/onTempChannel/types.ts
  src/actions/index.ts
  src/actions/onVoiceStateUpdate.ts
  src/index.ts
  src/types.ts
  src/utils/botConfig.ts
Labels: enhancement, feature

#55 Role Organize System Implementation
  src/actionHandlers/index.ts
  src/actionHandlers/onRoleOrganize.ts
  src/actions/index.ts
  src/actions/onGuildMemberUpdate.ts
  src/types.ts
  src/utils/botConfig.ts
  src/utils/helpers.ts
Labels: enhancement, feature

#54 After temp channels bugs
  src/actionHandlers/commands/index.ts
  src/actionHandlers/onTempChannel/helpers.ts
  src/actionHandlers/onTempChannel/onEveryTempChannel.ts
  src/actionHandlers/onTempChannel/onTempChannel.ts
  src/localdb/helpers.ts
  src/localdb/index.ts
Labels: bug, enhancement, feature, refactor

#56 Preparing the bot for production
  src/actionHandlers/commands/avatar.ts
  src/actionHandlers/commands/clearChat.ts
  src/actionHandlers/commands/commands.ts
  src/actionHandlers/commands/diceRoll.ts
  src/actionHandlers/commands/index.ts
  src/actionHandlers/commands/lockChannel.ts
  src/actionHandlers/commands/modHelp.ts
  src/actionHandlers/commands/serverConfig.ts
  src/actionHandlers/commands/serverInfo.ts
  src/actionHandlers/commands/serverStatus.ts
  src/actionHandlers/commands/slowMode.ts
  src/actionHandlers/commands/types.ts
  src/actionHandlers/commands/unlockChannel.ts
  src/actionHandlers/commands/user.ts
  src/actionHandlers/commands/warn.ts
  src/actionHandlers/onAutoBan.ts
  src/actionHandlers/onCustomStatus.ts
  src/actionHandlers/onLinkSend.ts
  src/actionHandlers/onPing.ts
  src/actionHandlers/onRoleOrganize.ts
  src/actionHandlers/onServerConfig/helpers.ts
  src/actionHandlers/onServerConfig/index.ts
  src/actionHandlers/onServerConfig/types.ts
  src/actionHandlers/onServerStatus/addStatus.ts
  src/actionHandlers/onServerStatus/helpers.ts
  src/actionHandlers/onServerStatus/index.ts
  src/actionHandlers/onServerStatus/removeStatus.ts
  src/actionHandlers/onTempChannel/helpers.ts
  src/actionHandlers/onTempChannel/onEveryTempChannel.ts
  src/actionHandlers/onTempChannel/onTempChannel.ts
  src/actionHandlers/onWelcome.ts
  src/actions/action.ts
  src/actions/index.ts
  src/actions/onGuildCreate.ts
  src/actions/onGuildMemberAdd.ts
  src/actions/onGuildMemberUpdate.ts
  src/actions/onInteractionCreate.ts
  src/actions/onMessageCreate.ts
  src/actions/onReady.ts
  src/actions/onVoiceStateUpdate.ts
  src/actions/types.ts
  src/db/ServerSchema.ts
  src/db/UserSchema.ts
  src/db/helpers.ts
  src/db/index.ts
  src/index.ts
  src/localdb/helpers.ts
  src/localdb/index.ts
  src/localdb/types.ts
  src/types.ts
  src/utils/botConfig.ts
  src/utils/helpers.ts
  src/utils/index.ts
  src/utils/onCrash.ts
Labels: enhancement, feature, refactor

#57 Invalid Server Config
  src/actionHandlers/onServerConfig/helpers.ts
Labels: bug, enhancement, refactor

#58 Reimplement one has siblings role organize feature
  src/actionHandlers/onRoleOrganize.ts
Labels: bug, enhancement, refactor

#59 Maintenance Interaction Implementation
  src/actionHandlers/commands/commands.ts
  src/actionHandlers/commands/maintenance.ts
  src/actionHandlers/onMaintenance/index.ts
  src/actionHandlers/onMaintenance/onMaintenance.ts
  src/types.ts
  src/utils/botConfig.ts
Labels: enhancement, feature
