Repository GalacticsTeam/galactics-bot-enhanced, pull requests merged in 2024-06, with the labels that each got.

#35 [GTB-22] Slow mode interaction implementaion
  src/actionHandlers/commands/index.ts
  src/actionHandlers/commands/slowMode.ts
  src/utils/botConfig.ts
Labels: enhancement, feature

#36 [GTB-36] Simplify interaction creation process
  src/actionHandlers/commands/index.ts
  src/actionHandlers/commands/types.ts
  src/utils/helpers.ts
Labels: enhancement, feature, refactor

#30 [GTB-14] Welcome message implementation
  package-lock.json
  package.json
  src/actionHandlers/onWelcome.ts
  src/actions/index.ts
  src/actions/onGuildMemberAdd.ts
  src/assets/welcomeImage.png
Labels: enhancement, feature

#37 [GTB-8] Custom status implementation
  src/actionHandlers/onCustomStatus.ts
  src/actions/onReady.ts
  src/utils/botConfig.ts
Labels: enhancement, feature

#38 Prefix Handling Implementation
  src/actionHandlers/index.ts
  src/actionHandlers/onPrefix.ts
  src/actionHandlers/prefixes/types.ts
  src/actions/onMessageCreate.ts
  src/types.ts
Labels: enhancement, feature

#39 Use type safety to automate commands creation
  src/actionHandlers/commands/index.ts
  src/actionHandlers/commands/types.ts
Labels: bug, enhancement, refactor

#40 [GTB-46] lock channel interaction implementation
  src/actionHandlers/commands/index.ts
  src/actionHandlers/commands/lockChannel.ts
  src/utils/botConfig.ts
Labels: enhancement, feature

#41 [GTB-47] unlock channel interaction implementation
  src/actionHandlers/commands/index.ts
  src/actionHandlers/commands/unlockChannel.ts
  src/utils/botConfig.ts
Labels: enhancement, feature

#34 [GTB-1] Database Implementation
  package-lock.json
  src/actions/onGuildMemberAdd.ts
  src/utils/botConfig.ts
Labels: enhancement, feature, refactor

#42 [GTB-4] Database Implementation to the all features
  package-lock.json
  src/actionHandlers/commands/lockChannel.ts
  src/actionHandlers/commands/serverConfig.ts
  src/actionHandlers/commands/unlockChannel.ts
  src/actionHandlers/onWelcome.ts
  src/actions/onGuildMemberAdd.ts
  src/db/ServerSchema.ts
  src/types.ts
  src/utils/botConfig.ts
Labels: enhancement, feature

#43 Implement list all server config interaction
  src/actionHandlers/commands/serverConfig.ts
Labels: enhancement, feature

#44 Auto ban implementation
  src/actionHandlers/onAutoBan.ts
  src/db/ServerSchema.ts
  src/db/UserSchema.ts
  src/types.ts
  src/utils/botConfig.ts
Labels: enhancement, feature

#45 Implement LocalDb system
  localdb/package-lock.json
  localdb/package.json
  package-lock.json
  package.json
  src/actions/onReady.ts
  src/localdb/helpers.ts
  src/localdb/index.ts
  src/localdb/types.ts
  src/types.ts
  src/utils/botConfig.ts
Labels: enhancement, feature

#46 Implement Repeated Welcomes
  src/actionHandlers/onWelcome.ts
  src/types.ts
  src/utils/botConfig.ts
Labels: enhancement, feature

#47 Auto Response System Implementation with interactions
  src/actionHandlers/commands/index.ts
  src/actionHandlers/commands/modHelp.ts
  src/db/ServerSchema.ts
  src/types.ts
  src/utils/botConfig.ts
Labels: enhancement, feature
