Repository GalacticsTeam/galactics-bot-enhanced, pull requests merged in 2024-05, with the labels that each got.

#1 Bot Files Setup
  package-lock.json
  package.json
  src/actionHandlers/index.ts
  src/actions/action.ts
  src/actions/index.ts
  src/actions/onReady.ts
  src/index.ts
  src/types.ts
  src/utils/botConfig.ts
  src/utils/crashHandling.ts
  src/utils/index.ts
Labels: enhancement

#10 Interactions Implementation
  src/actionHandlers/commands/diceRoll.ts
  src/actionHandlers/commands/index.ts
  src/actionHandlers/commands/types.ts
  src/actionHandlers/index.ts
  src/actions/index.ts
  src/actions/onInteractionCreate.ts
  src/actions/onReady.ts
  src/types.ts
  src/utils/botConfig.ts
Labels: enhancement

#11 Avatart interaction implementation
  src/actionHandlers/commands/avatar.ts
  src/actionHandlers/commands/index.ts
  src/types.ts
  src/utils/botConfig.ts
Labels: enhancement

#12 User data Implementation
  src/actionHandlers/commands/index.ts
  src/actionHandlers/commands/user.ts
  src/types.ts
  src/utils/botConfig.ts
Labels: enhancement, feature

#13 Update interaction creation type system, update tsconfig file
  .gitignore
  src/actionHandlers/commands/avatar.ts
  src/actionHandlers/commands/diceRoll.ts
  src/actionHandlers/commands/index.ts
  src/actionHandlers/commands/types.ts
  src/actionHandlers/commands/user.ts
  src/actionHandlers/onPing.ts
  src/actions/index.ts
  src/actions/onInteractionCreate.ts
  src/actions/onReady.ts
  src/types.ts
  src/utils/botConfig.ts
  src/utils/index.ts
  tsconfig.json
Labels: enhancement, feature

#14 Refactor avatar command
  src/actionHandlers/commands/avatar.ts
Labels: enhancement, refactor

#16 Refactor user command
  src/actionHandlers/commands/user.ts
Labels: enhancement, refactor

#17 Deployment updates
  .gitignore
  src/actionHandlers/commands/avatar.ts
  src/actionHandlers/commands/diceRoll.ts
  src/actionHandlers/commands/index.ts
  src/actionHandlers/commands/types.ts
  src/actionHandlers/commands/user.ts
  src/actionHandlers/index.ts
  src/actionHandlers/onPing.ts
  src/actions/index.ts
  src/actions/onInteractionCreate.ts
  src/actions/onMessageCreate.ts
  src/actions/onReady.ts
  src/types.ts
  src/utils/botConfig.ts
  src/utils/index.ts
  tsconfig.json
Labels: enhancement, feature, refactor

#19 Conditional Client login
  src/index.ts
  src/utils/botConfig.ts
Labels: enhancement, feature

#20 Merge
  src/index.ts
  src/utils/botConfig.ts
Labels: enhancement, feature

#21 Fix npm scripts and typescript not working properly
  package-lock.json
  package.json
  tsconfig.json
Labels: bug, enhancement, refactor

#24 Fix npm and typesctipt problems
  package-lock.json
  package.json
  src/actionHandlers/commands/index.ts
  src/actions/onReady.ts
  src/utils/index.ts
  tsconfig.json
Labels: bug, enhancement, refactor

#26 Improve allowed feature handling
  package.json
  src/actionHandlers/commands/index.ts
  src/actionHandlers/onPing.ts
  src/actions/onMessageCreate.ts
  src/types.ts
  src/utils/helpers.ts
Labels: enhancement, feature, refactor

#25 Link blocking implementation
  .prettierrc.json
  src/actionHandlers/index.ts
  src/actionHandlers/onLinkSend.ts
  src/actions/onMessageCreate.ts
  src/types.ts
  src/utils/botConfig.ts
Labels: enhancement, feature

#28 Enable all features for production
  src/actionHandlers/onPing.ts
  src/utils/botConfig.ts
Labels: enhancement

#27 Clear interaction Implementation
  src/actionHandlers/commands/clearChat.ts
  src/actionHandlers/commands/index.ts
  src/utils/botConfig.ts
Labels: enhancement, feature

#29 Fix the app not building correctly on production
  package-lock.json
  src/actionHandlers/commands/index.ts
  src/actions/onMessageCreate.ts
  src/utils/helpers.ts
  tsconfig.json
Labels: bug, enhancement

#31 Move interactions related types to its correct place
  src/actionHandlers/commands/index.ts
  src/actionHandlers/commands/types.ts
  src/types.ts
Labels: enhancement, feature, refactor

#32 Implement server-info interaction
  src/actionHandlers/commands/index.ts
  src/actionHandlers/commands/serverInfo.ts
  src/utils/botConfig.ts
Labels: enhancement, feature

#33 Interactions creation and handling automation
  src/actionHandlers/commands/avatar.ts
  src/actionHandlers/commands/clearChat.ts
  src/actionHandlers/commands/diceRoll.ts
  src/actionHandlers/commands/index.ts
  src/actionHandlers/commands/serverInfo.ts
  src/actionHandlers/commands/types.ts
  src/actionHandlers/commands/user.ts
  src/actions/onInteractionCreate.ts
  src/types.ts
  src/utils/botConfig.ts
  src/utils/helpers.ts
Labels: enhancement, feature, refactor
